---
title: "PVV Validation Analysis"
output: html_notebook
---

This notebook will look at the prediction accuracy of $\simga^2_{G(m)}$ and $\mu_{SP(m)}$ in the PopVarVal project

## Introduction

```{r setup}
library(tidyverse)
library(lme4)
library(modelr)
library(readxl)
library(stringr)
library(broom)
library(pbr)
library(purrrlyr)
library(boot)

# Project directory
proj_dir <- "C:/Users/Jeff/Google Drive/Barley Lab/Projects/PopVarVal/"

proj_pheno_dir <- file.path(proj_dir, "Phenotypic_Data")
result_dir <- file.path(proj_dir, "/Results/")
pred_dir <- file.path(proj_dir, "Predictions")
entry_dir <- file.path(proj_dir, "Plant_Material")

# Read in cross information
cross_list <- read_excel(file.path(entry_dir, "PopVarVal_cross_info.xlsx")) %>%
  mutate(Cross_no = str_c("4", F1_Pot_No))

# Load the predictions
load(file.path(result_dir, "PVV_post_hoc_prediction_results.RData"))
# Load the observations
load(file.path(result_dir, "PVV_varG_estimates.RData" ))



```



## Results

Calculate superior progeny mean of the BLUPs

```{r}

i_sp <- 0.10
# All traits will be selected on the lower tail
PVV_family_musp <- PVV_family_varG %>% 
  select(trait, family, prog_BLUE) %>% 
  unnest() %>%
  group_by(trait, family) %>%
  mutate(mu = mean(value)) %>%
  mutate(n_ind = n(),
         # Get quantile of i_sp
         i_sp_q = quantile(value, i_sp)) %>%
  filter(value <= i_sp_q) %>%
  summarize(mu_sp = mean(value),
            mu = mean(mu)) %>%
  gather(metric, estimate, -trait, -family)

# How many individuals per family
PVV_family_varG %>% 
  select(trait, family, prog_BLUE) %>% 
  unnest() %>% 
  group_by(family) %>% 
  summarize(fam_size = n_distinct(line_name)) %>%
  arrange(desc(fam_size))

# Number of families per trait
PVV_family_varG %>% 
  select(trait, family, prog_BLUE) %>% 
  unnest() %>% 
  group_by(trait) %>% 
  summarize(n_fam = n_distinct(family))


```


Accuracy to Predict Variance and Superior Projeny


```{r var.acc}

# Combine predicted vs observed variances
PVV_varG_comb <- left_join(select(PVV_family_varG, trait, family, varG_hat, h),
                          select(PVV_family_pred, cross:experiment, trait, pred.varG),
                          by = c("trait", "family" = "cross"))

# Function for bootstrapping
cor1 <- function(input.data, i) {
    rep_data <- input.data[i,]
    return(cor(rep_data[,1], rep_data[,2], use = "complete.obs"))
  }

# For each trait, estimate the correlation between predicted and observed VarG
# Use bootstrapping to get a confidence interval
(PVV_varG_acc <- PVV_varG_comb %>% 
  group_by(trait) %>% 
  filter(!is.na(pred.varG)) %>%
  do({
    boot_out <- boot(data = cbind(.$varG_hat, .$pred.varG), statistic = cor1,
                     R = 1000)
    data_frame(statistic = boot_out$t0, se = sd(boot_out$t), 
               bias = mean(boot_out$t) - boot_out$t0,
               ci_lower = quantile(boot_out$t, 0.025),
               ci_upper = quantile(boot_out$t, 0.975),
               n_obs = nrow(boot_out$data)) }))

## Plot
PVV_varG_comb %>%
  left_join(., PVV_varG_acc) %>%
  ggplot(aes(x = pred.varG, y = varG_hat)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_text(aes(x = Inf, y = -Inf, label = str_c("r = ", round(statistic, 3)), vjust = -1, hjust = 1.5)) +
  ylab("Estimated Genetic Variance") +
  xlab("Predicted Genetic Variance") +
  facet_wrap(~ trait, ncol = 2, scales = "free") +
  theme_bw()
    
    

```

Accuracy to predict superior progeny mean

```{r mu.sp.acc}

# Combine predicted vs observed variances
PVV_musp_comb <- left_join(PVV_family_musp, select(PVV_family_pred, cross:experiment, trait, mu = pred.mu, mu_sp = mu.sp_low) %>% 
                             gather(metric, prediction, -cross:-trait),
                          by = c("trait", "family" = "cross", "metric"))
  

# For each trait, estimate the correlation between predicted and observed VarG
# Use bootstrapping to get a confidence interval
(PVV_musp_acc <- PVV_musp_comb %>% 
  group_by(trait, metric) %>% 
  filter(!is.na(prediction)) %>%
  do({
    boot_out <- boot(data = cbind(.$estimate, .$prediction), statistic = cor1,
                     R = 1000)
    data_frame(statistic = boot_out$t0, se = sd(boot_out$t), 
               bias = mean(boot_out$t) - boot_out$t0,
               ci_lower = quantile(boot_out$t, 0.025),
               ci_upper = quantile(boot_out$t, 0.975),
               n_obs = nrow(boot_out$data)) }))
## Plot
PVV_musp_comb %>%
  left_join(., PVV_musp_acc) %>%
  ggplot(aes(x = prediction, y = estimate)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_text(aes(x = Inf, y = -Inf, label = str_c("r = ", round(statistic, 3)), vjust = -1, hjust = 1.5)) +
  ylab("Estimate") +
  xlab("Prediction") +
  facet_wrap(trait ~ metric, ncol = 2, scales = "free") +
  theme_bw()
    

# Combine
PVV_acc_comb <- PVV_varG_comb %>%
  select(trait, family, estimate = varG_hat, prediction = pred.varG, names(.)) %>% 
  mutate(metric = "varG") %>%
  bind_rows(., PVV_musp_comb) %>%
  select(trait, family, metric, names(.)) %>%
  ungroup()

# SAve
save_file <- file.path(result_dir, "PVV_pred_est_combined.RData")
save("PVV_acc_comb", file = save_file)


## Plot
PVV_acc_comb %>%
  mutate(metric = str_replace_all(string = metric, c("mu_sp" = "SuperiorProgenyMean", "mu" = "Mean", "varG" = "GeneticVariance")),
         metric = as.factor(metric),
         metric = `levels<-`(metric, c("Mean", "GeneticVariance", "SuperiorProgenyMean"))) %>%
  ggplot(aes(x = prediction, y = estimate)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  ylab("Estimate") +
  xlab("Prediction") +
  facet_wrap(trait ~ metric, ncol = 3, scales = "free") +
  theme_bw()


```


